#!/bin/sh
ssh ubuntu@ec2-52-79-242-108.ap-northeast-2.compute.amazonaws.com <<EOF
    cd ~/jenkins_test		
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 16.16.0
    npm install
    npm install -g typescript
    npm install -g ts-node
    npm install -g pm2
    pm2 install typescript
    pm2 restart ecosystem.config.js
    exit
EOF